development:
  adapter: postgresql
  encoding: utf8
  database: hotskippy_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hotskippy_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: hotskippy_app
  pool: 5
